In [42]:
import pandas as pd 
data = pd.read_csv('C:\\Users\\prath\\OneDrive\\Documents\\GitHub\\kidney-tumor-detection\\data\\raw\\kidneyData.csv')

In [43]:
data.head(2)

,Unnamed: 0,image_id,path,diag,target,Class
0,0,Tumor- (1044),"/content/data/CT KIDNEY DATASET Normal, CYST, ...",Tumor,3,Tumor
1,1,Tumor- (83),"/content/data/CT KIDNEY DATASET Normal, CYST, ...",Tumor,3,Tumor

In [25]:
data.columns

Index(['Unnamed: 0', 'image_id', 'path', 'diag', 'target', 'Class'], dtype='object')

In [26]:
data.drop(columns=['Unnamed: 0','path','diag','Class'])

            image_id  target
0      Tumor- (1044)       3
1        Tumor- (83)       3
2       Tumor- (580)       3
3      Tumor- (1701)       3
4      Tumor- (1220)       3
...              ...     ...
12441   Cyst- (2522)       0
12442   Cyst- (2627)       0
12443    Cyst- (972)       0
12444   Cyst- (2323)       0
12445   Cyst- (2145)       0

[12446 rows x 2 columns]

In [27]:
relation_map = {
    0: 'Cyst',
    1: 'Normal',
    2: 'Stone',
    3: 'Tumor'
}

In [41]:
#Let's reconstruct image path from image-id

from PIL import Image
import os

for i in data['image_id']:
    base = r"C:\Users\prath\OneDrive\Documents\GitHub\kidney-tumor-detection\data\raw\images"

    image_path = os.path.join(base, f"{i}.jpg")
    print("Looking for image at:", image_path)

    try:
        img = Image.open(image_path)
        img.show()
    except FileNotFoundError:
        print(f"Error: The file {i}.jpg was not found in the raw directory.")
        
    break

Looking for image at: C:\Users\prath\OneDrive\Documents\GitHub\kidney-tumor-detection\data\raw\images\Tumor- (1044).jpg